# Generated by Django 5.2.14 on 2026-05-17 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="created_at",
        ),
        migrations.AlterField(
            model_name="book",
            name="publish_year",
            field=models.PositiveIntegerField(verbose_name="Год издания"),
        ),
    ]
