# Generated by Django 5.2.14 on 2026-05-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_book_created_by_book_writer_alter_book_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="books/covers/",
                verbose_name="Обложка книги",
            ),
        ),
    ]
